### PR TITLE
Fix compilation errors for modern Xcode versions

### PR DESCRIPTION
**Pull request by and**
- Works on Mac OS Tahoe 26.2
- Fix incompatible function pointer types in LinkingEditor.m by adding explicit IMP cast
- Fix incompatible function pointer types in GlobalPrefs.m by adding explicit cast
- Remove deprecated -whatsloaded linker flag from project settings

These changes allow the project to build successfully on Xcode 16 with macOS SDK 26.2.

Screenshot 2026-02-08 at 9 19 16 AM

### CODE REVIEW

**Comment by scrod** [comment]
I have a considerably more advanced version that fixes the issues you mentioned; I will push it soon.
